### PR TITLE
e2etemplates: rename package directory to deprecated_e2etemplates

### PR DESCRIPTION
**Pull request by kopiczko**
This is to indicate that nothing new should land in this directory.

Note that package name and imports stay the same.

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
LGTM once the CI error about the legal files is fixed. Thanks for sorting this.

**Comment by xh3b4sd** [comment]
Breaking change information for everyone in the description and Slack would be pretty grand. Took a while to understand why my shit fails. 

```
$ dep ensure -update
Solving failure: No versions of github.com/giantswarm/e2etemplates met constraints:
	master: Could not introduce github.com/giantswarm/e2etemplates@master, as its subpackage github.com/giantswarm/e2etemplates/pkg/e2etemplates is missing. (Package is required by (root).)
	add_app_catalog: Could not introduce github.com/giantswarm/e2etemplates@add_app_catalog, as it is not allowed by constraint master from project github.com/giantswarm/aws-operator.
	chart-crd: Could not introduce github.com/giantswarm/e2etemplates@chart-crd, as it is not allowed by constraint master from project github.com/giantswarm/aws-operator.
	node-operator: Could not introduce github.com/giantswarm/e2etemplates@node-operator, as it is not allowed by constraint master from project github.com/giantswarm/aws-operator.
```

**Comment by kopiczko** [comment]
Oh shit, sorry I didn't realize this is a breaking change. The package name stayed the same. It was only the directory name that changed. I thought it won't affect vendoring.

**Comment by kopiczko** [comment]
See https://github.com/giantswarm/e2etemplates/pull/56

**Pull request merged**
