### PR TITLE
Add app and catalog e2e template

### PR DESCRIPTION
**Pull request by tomahawk28**

### CODE REVIEW

**Comment by kopiczko** [comment]
`pkg/e2etemplates` package is outdated. Please switch to `pkg/chartvalues` and add tests.

**Comment by rossf7** [comment]
If `pkg/e2etemplates` is outdated we should add a deprecation message to the readme.

**Comment by kopiczko** [comment]
@rossf7: check https://github.com/giantswarm/e2etemplates/pull/54.

**Comment by rossf7** [comment]
@tomahawk28 Looks like this is outdated. Can it be closed?

**Comment by rossf7** [comment]
@tomahawk28 Can this be closed?

**Comment by tomahawk28** [comment]
@rossf7 Sure

**Pull request closed without merging**
