### PR TITLE
chartvalues: aws-operator chart fixes

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/3892

### CODE REVIEW

**Comment by kopiczko** [comment]
Tested with https://github.com/giantswarm/aws-operator/pull/1104

**Review by xh3b4sd — APPROVED** [review]
When this works for you lets go. Lets just make sure that the operator is properly aligned so nobody gets blocked this time.

**Comment by kopiczko** [comment]
All tested this time https://circleci.com/workflow-run/e24d9b53-7414-4dd2-8242-b667706a15bc

**Review by TheoBrigitte — APPROVED** [review]
LGTM

**Pull request merged**
